jobs:
  CloneRepo:
    uses: git-checkout@v1
    with:
      url: https://github.com/Jameshskelton/workflow-test.git
    outputs:
      repo:
        type: volume
    resources:
      instance-type: C5
  workflow-test:
    uses: script@v1
    with:
      image: tensorflow/tensorflow:1.14.0-gpu-py3
      script: |-
        pip3 install -U scikit-learn
        pip3 install pandas
        cd /inputs/repo
        python3 model_iris.py make_prediction \
          --network=mosygl1eabx1z7o \
          --data=dst5ycz7ehnkv5u \
          --result-dir=/outputs/iris
        mv predSpecies1.csv /outputs/iris
        ls "-aFlR" /outputs/iris
    needs:
      - CloneRepo
    inputs:
      repo: CloneRepo.outputs.repo
    outputs:
      iris:
        type: dataset
        with:
          ref: dst5ycz7ehnkv5u
    resources:
      instance-type: C5